package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.*;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

import static utils.UIColors.*;

/**
 * Finestra di autenticazione per l'accesso e la registrazione degli utenti.
 * <p>
 * Nota Architetturale: Questa classe rappresenta il Layer Boundary.
 * Delega ogni operazione logica al Controller ricevuto nel costruttore e
 * utilizza un CardLayout per ottimizzare la transizione tra Login e Registrazione.
 */
public class AuthFrame extends JFrame {
    private JPanel rootPanel;
    private JPanel hackathonIoPanel;
    private JLabel hackathonIoLabel;
    private JPanel sidePanel;
    private JPanel cardPanel;
    private CardLayout cardLayout;
    private final transient Controller controller;

    /**
     * Costruttore della finestra di autenticazione.
     *
     * @param controller Il controllore principale dell'architettura BCE.
     */
    public AuthFrame(Controller controller) {
        this.controller = controller;

        setTitle("Hackathon.IO - Access");
        setSize(600, 450);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setContentPane(rootPanel);

        customizeComponents();
        setupCardPanel();
    }

    /**
     * Personalizza i componenti estetici applicando i colori centralizzati di sistema.
     */
    private void customizeComponents() {
        sidePanel.setBackground(NIGHT_BLUE);
        hackathonIoPanel.setBackground(NIGHT_BLUE);
        hackathonIoLabel.setForeground(Color.WHITE);
    }

    /**
     * Inizializza il pannello centrale sfruttando il CardLayout per iniettare
     * le viste di login e di registrazione in modo dinamico.
     */
    private void setupCardPanel() {
        cardLayout = new CardLayout();
        cardPanel.setLayout(cardLayout);

        LoginCardPanel loginPanel = new LoginCardPanel(cardPanel, controller);
        cardPanel.add(loginPanel.getRootPanel(), "login");

        RegistrationCardPanel registrationPanel = new RegistrationCardPanel(cardPanel, controller);
        cardPanel.add(registrationPanel.getRootPanel(), "register");

        cardLayout.show(cardPanel, "login");
    }

    /**
     * Restituisce il pannello root della finestra.
     *
     * @return L'istanza di rootPanel.
     */
    public JPanel getRootPanel() {
        return rootPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        sidePanel = new JPanel();
        sidePanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(sidePanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        hackathonIoPanel = new JPanel();
        hackathonIoPanel.setLayout(new GridLayoutManager(1, 1, new Insets(20, 20, 20, 20), -1, -1));
        sidePanel.add(hackathonIoPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        hackathonIoLabel = new JLabel();
        Font hackathonIoLabelFont = this.$$$getFont$$$(null, -1, 26, hackathonIoLabel.getFont());
        if (hackathonIoLabelFont != null) hackathonIoLabel.setFont(hackathonIoLabelFont);
        hackathonIoLabel.setText("Hackathon.io");
        hackathonIoPanel.add(hackathonIoLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cardPanel = new JPanel();
        cardPanel.setLayout(new CardLayout(0, 0));
        rootPanel.add(cardPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}