package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.Controller;
import utils.RoundedPanel;
import utils.UIColors;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Dialogo modale per il caricamento di documenti e link di progetto (Layer Boundary).
 * <p>
 * Nota Architetturale: Questa classe gestisce esclusivamente l'interazione utente.
 * La validazione dei permessi e la persistenza dei dati sono delegate al Controller
 * per garantire il rispetto dei principi BCE e DRY.
 */
public class DocumentUploadDialog extends JDialog {

    private static final Logger LOGGER = Logger.getLogger(DocumentUploadDialog.class.getName());

    private JPanel rootPanel;
    private JTextField nameField;
    private JTextField urlField;
    private JPanel rUploadPanel;
    private JLabel uploadLabel;

    /**
     * Inizializza il dialogo di caricamento documenti.
     *
     * @param parent     Il frame genitore per la modalità della finestra.
     * @param controller Il coordinatore centrale del sistema.
     */
    public DocumentUploadDialog(JFrame parent, Controller controller) {
        super(parent, "Upload Document", true);

        $$$setupUI$$$();
        setContentPane(rootPanel);
        setSize(400, 300);
        setLocationRelativeTo(parent);
        setResizable(false);

        customizeStyle();
        setupListeners(controller);
    }

    /**
     * Configura l'estetica del pannello utilizzando i colori centralizzati.
     */
    private void customizeStyle() {
        rUploadPanel.setBackground(UIColors.NIGHT_BLUE);
        uploadLabel.setForeground(Color.WHITE);
        rUploadPanel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    /**
     * Configura i listener per la gestione dell'upload e degli effetti hover.
     *
     * @param controller Istanza del Controller per l'esecuzione dell'azione.
     */
    private void setupListeners(Controller controller) {
        rUploadPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                processUpload(controller);
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                rUploadPanel.setBackground(UIColors.CARMINE_RED);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                rUploadPanel.setBackground(UIColors.NIGHT_BLUE);
            }
        });
    }

    /**
     * Esegue la logica di validazione superficiale e invoca il Controller.
     */
    private void processUpload(Controller controller) {
        String name = nameField.getText().trim();
        String url = urlField.getText().trim();

        if (name.isEmpty() || url.isEmpty()) {
            JOptionPane.showMessageDialog(rootPanel, "All fields are required!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Delega l'azione al Controller (Layer Control)
            controller.addDocumentAction(name, url);

            LOGGER.log(Level.INFO, "User initiated document upload: {0}", name);
            JOptionPane.showMessageDialog(rootPanel, "Document uploaded successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (IllegalStateException ex) {
            // Gestione di errori di stato (es. utente non partecipante)
            LOGGER.log(Level.WARNING, "Upload blocked by controller: {0}", ex.getMessage());
            JOptionPane.showMessageDialog(rootPanel, ex.getMessage(), "Access Denied", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            // Gestione errori imprevisti o SQL propagati dai DAO
            LOGGER.log(Level.SEVERE, "Unexpected error during document upload", ex);
            JOptionPane.showMessageDialog(rootPanel, "An error occurred while uploading. Please try again.", "System Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Inizializzazione manuale dei componenti custom richiesti dal designer.
     */
    private void createUIComponents() {
        rUploadPanel = new RoundedPanel();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(6, 1, new Insets(20, 20, 20, 20), -1, -1));
        rootPanel.setBackground(new Color(-1));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("SansSerif", Font.BOLD, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Upload Your Link !");
        rootPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        nameField = new JTextField();
        nameField.setText("");
        nameField.setToolTipText("Es: Repository GitHub, Presentazione...");
        rootPanel.add(nameField, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        urlField = new JTextField();
        urlField.setToolTipText("https://...");
        rootPanel.add(urlField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer2 = new Spacer();
        rootPanel.add(spacer2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        rUploadPanel.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        rootPanel.add(rUploadPanel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 40), null, 0, false));
        uploadLabel = new JLabel();
        Font uploadLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, uploadLabel.getFont());
        if (uploadLabelFont != null) uploadLabel.setFont(uploadLabelFont);
        uploadLabel.setText("Upload Document");
        rUploadPanel.add(uploadLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}